"use client";

import { useState } from "react";
import Link from "next/link";
import supplementsData from "@/data/supplements.json";

type TimeSlot = "morning_empty" | "morning_meal" | "afternoon" | "evening_meal" | "bedtime";

interface ScheduleItem {
  id: string;
  name: string;
  dose: string;
  slot: TimeSlot;
  withFood: boolean;
  notes: string;
  cycling: string | null;
}

const slotConfig: Record<TimeSlot, { label: string; time: string; icon: string }> = {
  morning_empty: { label: "Morning (Empty Stomach)", time: "6:00–7:00 AM", icon: "🌅" },
  morning_meal: { label: "Morning (With Breakfast)", time: "7:00–8:00 AM", icon: "☀️" },
  afternoon: { label: "Afternoon", time: "12:00–2:00 PM", icon: "🌤️" },
  evening_meal: { label: "Evening (With Dinner)", time: "6:00–7:00 PM", icon: "🌇" },
  bedtime: { label: "Before Bed", time: "9:00–10:00 PM", icon: "🌙" },
};

// Evidence-based optimal timing for each supplement
const timingMap: Record<string, { slot: TimeSlot; notes: string; cycling: string | null }> = {
  creatine: { slot: "morning_meal", notes: "Any time works — consistency matters most", cycling: null },
  "vitamin-d3": { slot: "morning_meal", notes: "Fat-soluble — take with largest meal", cycling: null },
  "vitamin-k2": { slot: "morning_meal", notes: "Pair with D3 and fat", cycling: null },
  "omega-3": { slot: "morning_meal", notes: "With fat-containing meal. Split dose if >2g", cycling: null },
  magnesium: { slot: "bedtime", notes: "Glycinate/threonate for sleep. Split if >200mg", cycling: null },
  ashwagandha: { slot: "bedtime", notes: "More sedating in evening. Sensoril especially", cycling: "8 weeks on, 2-4 weeks off" },
  caffeine: { slot: "morning_empty", notes: "30-60 min before desired effect. Cut off 8-10h before sleep", cycling: "5 days on, 2 off (or periodic 1-2 week washout)" },
  "l-theanine": { slot: "morning_empty", notes: "Best paired with caffeine. No tolerance develops", cycling: null },
  nmn: { slot: "morning_empty", notes: "Sublingual if available. Some take with food", cycling: null },
  coq10: { slot: "morning_meal", notes: "Ubiquinol preferred over 40. Take with fat", cycling: null },
  taurine: { slot: "morning_empty", notes: "Any time. Pre-workout if exercising", cycling: null },
  "protein-whey": { slot: "afternoon", notes: "Post-workout or any meal to hit protein target", cycling: null },
};

export default function ProtocolBuilderClient() {
  const [selected, setSelected] = useState<string[]>([]);
  const [copied, setCopied] = useState(false);

  function toggle(id: string) {
    setSelected((prev) =>
      prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]
    );
  }

  // Build schedule from selected supplements
  const schedule: ScheduleItem[] = selected
    .map((id) => {
      const s = supplementsData.find((x) => x.id === id);
      if (!s) return null;
      const timing = timingMap[id] || { slot: "morning_meal" as TimeSlot, notes: "", cycling: null };
      return {
        id: s.id,
        name: s.name,
        dose: s.dosing.standard,
        slot: timing.slot,
        withFood: s.dosing.withFood,
        notes: timing.notes,
        cycling: timing.cycling,
      };
    })
    .filter(Boolean) as ScheduleItem[];

  // Group by time slot
  const grouped = Object.entries(slotConfig)
    .map(([slot, cfg]) => ({
      slot: slot as TimeSlot,
      ...cfg,
      items: schedule.filter((s) => s.slot === slot),
    }))
    .filter((g) => g.items.length > 0);

  const cyclingItems = schedule.filter((s) => s.cycling);

  function exportText() {
    let text = "MY SUPPLEMENT PROTOCOL\n";
    text += "Generated by Supplement Stack (supplementstack.space)\n";
    text += "═".repeat(50) + "\n\n";
    grouped.forEach((g) => {
      text += `${g.icon} ${g.label} (${g.time})\n`;
      text += "─".repeat(40) + "\n";
      g.items.forEach((item) => {
        text += `  • ${item.name} — ${item.dose}\n`;
        if (item.notes) text += `    ${item.notes}\n`;
      });
      text += "\n";
    });
    if (cyclingItems.length > 0) {
      text += "⟳ CYCLING SCHEDULE\n";
      text += "─".repeat(40) + "\n";
      cyclingItems.forEach((item) => {
        text += `  • ${item.name}: ${item.cycling}\n`;
      });
    }
    return text;
  }

  async function copyProtocol() {
    await navigator.clipboard.writeText(exportText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <>
      <section className="bg-white border-b border-zinc-100">
        <div className="max-w-3xl mx-auto px-4 md:px-8 py-12 md:py-20">
          <nav className="mb-5 text-sm text-zinc-400">
            <Link href="/" className="hover:text-emerald-600">Home</Link>
            <span className="mx-1.5">/</span>
            <span className="text-zinc-900">Protocol Builder</span>
          </nav>
          <h1 className="font-serif text-3xl md:text-4xl font-bold text-zinc-900 tracking-tight mb-4">
            Protocol Builder
          </h1>
          <p className="text-base text-zinc-500 leading-relaxed max-w-xl">
            Select your supplements and get an optimized daily schedule with timing,
            food pairing, and cycling recommendations.
          </p>
        </div>
      </section>

      <div className="max-w-3xl mx-auto px-4 md:px-8 py-10 space-y-10">
        {/* Picker */}
        <section>
          <h2 className="text-sm font-semibold text-zinc-500 uppercase tracking-wider mb-4">
            Select Your Supplements
          </h2>
          <div className="flex flex-wrap gap-2">
            {supplementsData.map((s) => {
              const active = selected.includes(s.id);
              return (
                <button
                  key={s.id}
                  onClick={() => toggle(s.id)}
                  className={`px-4 py-2 rounded-full text-sm font-medium border transition-all ${
                    active
                      ? "bg-emerald-600 text-white border-emerald-600"
                      : "bg-white text-zinc-600 border-zinc-200 hover:border-zinc-300"
                  }`}
                >
                  {s.name}
                </button>
              );
            })}
          </div>
        </section>

        {/* Schedule */}
        {grouped.length > 0 && (
          <section className="space-y-6">
            <div className="flex items-center justify-between">
              <h2 className="font-serif text-2xl font-semibold text-zinc-900">Your Daily Protocol</h2>
              <button
                onClick={copyProtocol}
                className="text-sm font-medium text-emerald-600 hover:text-emerald-700 transition-colors"
              >
                {copied ? "✓ Copied!" : "Copy to clipboard"}
              </button>
            </div>

            {grouped.map((g) => (
              <div key={g.slot} className="bg-white border border-zinc-200 rounded-xl overflow-hidden">
                <div className="bg-zinc-50 px-5 py-3 border-b border-zinc-100 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="text-lg">{g.icon}</span>
                    <h3 className="font-semibold text-zinc-900 text-sm">{g.label}</h3>
                  </div>
                  <span className="text-xs text-zinc-400">{g.time}</span>
                </div>
                <div className="divide-y divide-zinc-50">
                  {g.items.map((item) => (
                    <div key={item.id} className="px-5 py-4">
                      <div className="flex items-center justify-between mb-1">
                        <span className="font-medium text-zinc-900 text-sm">{item.name}</span>
                        <span className="text-sm font-semibold text-emerald-600">{item.dose}</span>
                      </div>
                      <div className="flex items-center gap-2 text-xs text-zinc-400">
                        <span className={`px-1.5 py-0.5 rounded ${item.withFood ? "bg-emerald-50 text-emerald-600" : "bg-zinc-100 text-zinc-500"}`}>
                          {item.withFood ? "With food" : "Empty stomach OK"}
                        </span>
                        {item.notes && <span>· {item.notes}</span>}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}

            {/* Cycling */}
            {cyclingItems.length > 0 && (
              <div className="bg-amber-50 border border-amber-200 rounded-xl p-5">
                <h3 className="font-semibold text-amber-800 text-sm mb-3 flex items-center gap-2">
                  <span>⟳</span> Cycling Schedule
                </h3>
                <div className="space-y-2">
                  {cyclingItems.map((item) => (
                    <div key={item.id} className="flex items-center justify-between text-sm">
                      <span className="text-amber-700">{item.name}</span>
                      <span className="text-amber-600 font-medium">{item.cycling}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </section>
        )}

        {selected.length === 0 && (
          <div className="bg-zinc-50 border border-zinc-200 rounded-xl p-8 text-center">
            <p className="text-zinc-500">Select supplements above to generate your daily protocol.</p>
          </div>
        )}

        <div className="border-t border-zinc-100 pt-6">
          <p className="text-xs text-zinc-400 leading-relaxed">
            Timing recommendations are based on pharmacokinetics and absorption data from clinical research.
            Individual responses may vary. This is general guidance, not medical advice.
          </p>
        </div>
      </div>
    </>
  );
}
